In [1]:
from xml.dom.minidom import Entity
import pandas as pd
import numpy as np

In [39]:
datos_1 = pd.read_csv('datasets\Fuentes_Consumo_Energia.csv', delimiter=',', encoding='utf-8')
col_mex = datos_1[(datos_1.Entity=='Colombia')|(datos_1.Entity=='Mexico')]
tupla = (col_mex[col_mex.Entity=='Colombia'].shape[0],col_mex[col_mex.Entity=='Mexico'].shape[0])
tupla

(55, 55)

In [45]:
datos_2 = pd.read_csv('datasets\Fuentes_Consumo_Energia.csv', delimiter=',', encoding='utf-8')
datos_2.drop(columns=['Code','Entity'], inplace=True)
datos_2.shape

(5190, 9)

In [62]:
datos_3 = pd.read_csv('datasets\Fuentes_Consumo_Energia.csv', delimiter=',', encoding='utf-8')
datos_3.Year.count()
datos_3[datos_3.Entity=='World']

,Entity,Code,Year,Coal_Consumption_EJ,Gas_Consumption_EJ,Geo_Biomass_Other_TWh,Hydro_Generation_TWh,Nuclear_Generation_TWh,Solar_Generation_TWh,Wind_Generation_TWh,Oil_Consumption_EJ
5135,World,OWID_WRL,1965,58.104642,22.693676,17.985232,923.197924,25.539724,0.000000,0.000000,65.191064
5136,World,OWID_WRL,1966,58.766738,24.727660,19.806007,983.817037,34.433290,0.000000,0.000000,70.187240
5137,World,OWID_WRL,1967,57.818915,26.546542,19.986571,1005.742652,41.006014,0.000000,0.000000,75.206029
5138,World,OWID_WRL,1968,58.684128,28.959593,22.120045,1059.289008,52.113164,0.000000,0.000000,81.631612
5139,World,OWID_WRL,1969,60.475449,31.800305,23.257964,1121.743221,61.783412,0.000000,0.000000,88.476713
5140,World,OWID_WRL,1970,61.410989,34.613250,25.693196,1174.647576,78.874657,0.000000,0.000000,96.148951
5141,World,OWID_WRL,1971,61.077453,37.051894,27.879168,1227.065005,109.704177,0.000000,0.000000,101.537356
5142,World,OWID_WRL,1972,61.755597,39.100893,29.877101,1284.630368,152.175149,0.000000,0.000000,109.360591
5143,World,OWID_WRL,1973,63.604258,40.956192,32.084924,1303.009488,203.901579,0.000000,0.000000,117.886008
5144,World,OWID_WRL,1974,63.655384,41.962491,33.958814,1431.264984,266.600093,0.000000,0.000000,116.180700
5145,World,OWID_WRL,1975,64.888336,41.979868,34.483679,1448.889652,369.848191,0.000000,0.000000,115.014268
5146,World,OWID_WRL,1976,67.278546,44.478225,38.460956,1443.134706,432.671421,0.000000,0.000000,122.506826
5147,World,OWID_WRL,1977,69.268657,45.938261,40.562557,1491.671610,538.547814,0.000000,0.000000,126.772548
5148,World,OWID_WRL,1978,70.048429,47.863505,42.967478,1614.387725,625.794396,0.000000,0.003000,131.132756
5149,World,OWID_WRL,1979,73.308712,50.831542,46.169329,1695.189194,650.859895,0.000000,0.006000,133.286629
5150,World,OWID_WRL,1980,75.087367,51.256754,49.385364,1731.652451,711.924223,0.000000,0.010500,128.077938
5151,World,OWID_WRL,1981,76.138822,51.822424,53.154542,1768.903725,840.750762,0.000000,0.010500,123.465050
5152,World,OWID_WRL,1982,76.983922,52.087554,61.370557,1800.908921,912.177542,0.000000,0.018500,119.512468
5153,World,OWID_WRL,1983,79.362015,52.930047,68.017933,1877.769376,1033.812710,0.003000,0.032795,118.687360
5154,World,OWID_WRL,1984,82.798231,57.245573,76.009218,1941.375556,1254.568438,0.006311,0.044756,121.459551
5155,World,OWID_WRL,1985,86.350186,58.539220,77.792232,1979.774848,1488.921637,0.011747,0.064220,121.640963
5156,World,OWID_WRL,1986,87.321709,59.111564,85.579133,2006.571648,1594.735734,0.015184,0.138831,125.289699
5157,World,OWID_WRL,1987,90.756956,62.210148,91.642855,2033.706398,1734.733117,0.010603,0.195377,127.798039
5158,World,OWID_WRL,1988,93.472655,65.115382,94.280728,2098.720984,1891.249267,0.010196,0.331580,132.130978
5159,World,OWID_WRL,1989,94.368436,67.933928,104.348289,2087.570913,1945.010586,0.262223,2.649777,134.279354
5160,World,OWID_WRL,1990,93.221913,70.143914,116.960405,2158.906256,2000.462024,0.388295,3.632471,135.687082
5161,World,OWID_WRL,1991,92.313914,71.913766,121.982974,2209.410404,2096.174705,0.505203,4.086707,135.688309
5162,World,OWID_WRL,1992,91.979780,72.240456,130.941844,2209.074255,2112.089141,0.468585,4.733212,138.039613
5163,World,OWID_WRL,1993,92.430389,72.968711,135.281758,2341.244792,2184.826061,0.556698,5.697569,137.157255
5164,World,OWID_WRL,1994,92.784750,73.415970,140.409675,2356.881825,2225.844324,0.600014,7.122930,140.165762
5165,World,OWID_WRL,1995,93.435631,75.990775,146.361662,2485.633411,2322.395978,0.640814,8.261923,142.000783
5166,World,OWID_WRL,1996,95.659645,79.788390,150.565629,2520.498994,2406.801052,0.705208,9.204601,145.369674
5167,World,OWID_WRL,1997,95.496525,79.323616,161.286742,2566.135370,2390.276558,0.756585,12.017816,149.087611
5168,World,OWID_WRL,1998,94.894405,80.776449,168.762109,2586.942015,2431.380430,0.831789,15.921260,149.847835
5169,World,OWID_WRL,1999,95.478815,83.073461,177.393358,2605.676465,2524.361484,0.916197,21.216174,152.536859
5170,World,OWID_WRL,2000,98.702248,86.399524,186.055169,2651.961722,2580.899081,1.120230,31.420907,154.429764
5171,World,OWID_WRL,2001,100.268933,87.591338,191.884077,2583.887448,2653.767774,1.400821,38.390924,155.801239
5172,World,OWID_WRL,2002,104.200633,90.190364,206.361115,2631.846503,2696.170555,1.763901,52.331754,157.101019
5173,World,OWID_WRL,2003,113.387341,92.707167,217.925451,2627.603541,2641.568435,2.258381,62.916967,160.594131
5174,World,OWID_WRL,2004,121.191531,96.247986,235.283919,2820.744259,2761.605227,2.974844,85.117164,166.520411
5175,World,OWID_WRL,2005,130.214724,98.870027,254.588860,2916.350043,2768.867851,4.165618,104.085852,168.567165
5176,World,OWID_WRL,2006,137.054317,101.432266,271.693960,3027.673700,2803.366447,5.721249,132.859188,170.520457
5177,World,OWID_WRL,2007,144.804932,105.565226,294.784297,3079.335005,2746.239981,7.770396,170.730348,172.646921
5178,World,OWID_WRL,2008,146.773612,108.087502,315.503220,3257.388377,2737.707710,12.643679,220.649741,171.236202
5179,World,OWID_WRL,2009,144.534962,105.879619,339.648526,3252.497433,2698.983475,20.970909,276.052468,167.952483
5180,World,OWID_WRL,2010,151.189921,113.784267,379.876085,3435.834609,2768.505889,33.714780,346.505761,173.113552
5181,World,OWID_WRL,2011,158.464953,116.535487,398.735611,3501.067816,2652.680581,65.123596,440.617019,174.779772
5182,World,OWID_WRL,2012,159.067114,119.592019,430.760491,3649.723690,2470.805623,100.808404,530.852550,176.964050
5183,World,OWID_WRL,2013,161.976352,121.558003,463.988348,3814.040241,2493.401425,139.115242,635.774223,178.878495
5184,World,OWID_WRL,2014,161.835837,122.379306,500.911714,3894.178016,2541.138218,197.858428,706.469249,180.049011
5185,World,OWID_WRL,2015,157.838896,125.208335,538.277477,3884.619692,2575.763561,256.838045,831.567439,183.210968
5186,World,OWID_WRL,2016,155.504177,128.124027,547.865908,4012.947981,2614.905286,328.237428,963.774036,186.912413
5187,World,OWID_WRL,2017,156.094106,131.708206,582.893132,4065.869592,2638.554157,446.946764,1140.971268,189.242920
5188,World,OWID_WRL,2018,158.793935,138.659832,615.038237,4171.404951,2700.373917,582.754345,1270.164880,191.451896
5189,World,OWID_WRL,2019,157.857047,141.452770,651.811211,4222.214992,2795.961529,724.086506,1429.619982,193.031574

In [76]:
datos_4 = pd.read_csv('datasets\Fuentes_Consumo_Energia.csv', delimiter=',', encoding='utf-8')
datos_4.head()

,Entity,Code,Year,Coal_Consumption_EJ,Gas_Consumption_EJ,Geo_Biomass_Other_TWh,Hydro_Generation_TWh,Nuclear_Generation_TWh,Solar_Generation_TWh,Wind_Generation_TWh,Oil_Consumption_EJ
0,Africa,NaN,1965,1.164586,0.034358,0.0,13.905635,0.0,0.0,0.0,1.173241
1,Africa,NaN,1966,1.163240,0.038412,0.0,15.510004,0.0,0.0,0.0,1.284154
2,Africa,NaN,1967,1.189050,0.037964,0.0,16.190636,0.0,0.0,0.0,1.273799
3,Africa,NaN,1968,1.236646,0.038480,0.0,18.938341,0.0,0.0,0.0,1.344219
4,Africa,NaN,1969,1.247915,0.044971,0.0,22.100890,0.0,0.0,0.0,1.362729

In [68]:
datos_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5190 entries, 0 to 5189
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Entity                  5190 non-null   object
 1   Code                    4145 non-null   object
 2   Year                    5190 non-null   int64
 3   Coal_Consumption_EJ     5170 non-null   float64
 4   Gas_Consumption_EJ      5170 non-null   float64
 5   Geo_Biomass_Other_TWh   5115 non-null   float64
 6   Hydro_Generation_TWh    5170 non-null   float64
 7   Nuclear_Generation_TWh  5170 non-null   float64
 8   Solar_Generation_TWh    5170 non-null   float64
 9   Wind_Generation_TWh     5170 non-null   float64
 10  Oil_Consumption_EJ      5184 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 446.1+ KB

In [77]:
def thw_to_exj(numero):
  return 277.778*numero
datos_4[['Coal_Consumption_EJ','Gas_Consumption_EJ','Oil_Consumption_EJ']]=datos_4[['Coal_Consumption_EJ','Gas_Consumption_EJ','Oil_Consumption_EJ']].apply(thw_to_exj)
datos_4['Consumo_Total'] = datos_4['Coal_Consumption_EJ']+datos_4['Gas_Consumption_EJ']+datos_4['Oil_Consumption_EJ']+datos_4['Geo_Biomass_Other_TWh'] + datos_4['Hydro_Generation_TWh'] + datos_4['Nuclear_Generation_TWh'] + datos_4['Solar_Generation_TWh'] + datos_4['Wind_Generation_TWh']

In [81]:
float(datos_4[(datos_4.Entity=='World')&(datos_4.Year==2019)].Consumo_Total.round(2))

5189    146585.3
Name: Consumo_Total, dtype: float64

In [105]:
datos_5 = pd.read_csv('datasets\Fuentes_Consumo_Energia.csv', delimiter=',', encoding='utf-8')
europa = datos_5[datos_5.Entity=='Europe']
europa.reset_index(inplace=True)
indice_max = europa.Hydro_Generation_TWh.idxmax()
europa.iloc[indice_max].Year

2013

In [122]:
n1 = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
n2 = np.array([[6,7],[8,6],[7,8]])
n3 = np.array([[9,9],[10,10]])

def se_puede_hacer_broadcast(array1, array2):
    for a, b in zip(array1[::-1], array2[::-1]):
        if a.any() == 1 or b.any() == 1 or a.any() == b.any():
            pass
        else:
            return False
    return True

In [138]:
is_broadcastable(n1,n3)

True

In [128]:
n1.shape

(6, 3)

In [129]:
n2.shape

(3, 2)

In [130]:
n3.shape

(2, 2)

In [132]:
n3.shape > n2.shape

False

In [137]:
n1[::-1]

array([[5, 5, 5],
       [4, 4, 4],
       [3, 3, 3],
       [2, 2, 2],
       [1, 1, 1],
       [0, 0, 0]])

In [148]:
datos_7 = pd.read_csv('datasets\GGAL - Cotizaciones historicas.csv', delimiter=',', encoding='utf-8')
datos_7.maximo.sum().round(4)

202185.8933

In [159]:
datos_8 = pd.read_csv('datasets\Fuentes_Consumo_Energia.csv', delimiter=',', encoding='utf-8')
len(datos_8.Entity.unique())

100

In [162]:
tabla1 = pd.read_csv('datasets\Tabla1_ejercicio.csv', delimiter=';', encoding='utf-8')
tabla2 = pd.read_csv('datasets\Tabla2_ejercicio.csv', delimiter=';', encoding='utf-8')

In [169]:
datos_9 = pd.merge(tabla1, tabla2, on='pers_id')
datos_9.head()

,pers_id,sexo,edad,ingreso,situacion_lab,periodo,score
0,71906556521,F,47,35926.28125,Sin_situacion_declarada,201906,919
1,71906556521,F,47,35926.28125,Sin_situacion_declarada,201906,919
2,71906556521,F,47,35926.28125,Sin_situacion_declarada,201909,738
3,71906556521,F,47,35926.28125,Sin_situacion_declarada,201909,919
4,71906556521,F,47,35926.28125,Sin_situacion_declarada,201912,919

In [175]:
datos_9.drop_duplicates(inplace=True)
datos_9.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14721 entries, 0 to 15875
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pers_id        14721 non-null  int64
 1   sexo           14721 non-null  object
 2   edad           14721 non-null  int64
 3   ingreso        14721 non-null  float64
 4   situacion_lab  14721 non-null  object
 5   periodo        14721 non-null  int64
 6   score          14721 non-null  int64
dtypes: float64(1), int64(4), object(2)
memory usage: 920.1+ KB

In [167]:
datos_9.drop_duplicates(inplace=True, subset=['periodo', 'score'])
datos_9.head()

,pers_id,sexo,edad,ingreso,situacion_lab,periodo,score
0,71906556521,F,47,35926.28125,Sin_situacion_declarada,201906,919
2,71906556521,F,47,35926.28125,Sin_situacion_declarada,201909,738
3,71906556521,F,47,35926.28125,Sin_situacion_declarada,201909,919
4,71906556521,F,47,35926.28125,Sin_situacion_declarada,201912,919
12,73861260912,F,41,16231.12207,Sin_situacion_declarada,201906,557

In [176]:
score_prom_masculino = datos_9[(datos_9.sexo=='M')].score.mean()
score_prom_femenino = datos_9[(datos_9.sexo=='F')].score.mean()
(score_prom_masculino, score_prom_femenino)

(772.2811111111112, 630.261911750318)

In [181]:
import Lista as l
lis = l.Lista()